language: node_js
node_js:
  - stable
  - 6
  - 4
os:
  - linux
  - osx
osx_image: xcode7.3
matrix:
  fast_finish: true
script: yarn run travis
addons:
  code_climate:
    repo_token: bed43b4e75bf2687e85bbda02fea8033552d79331e070a22726846bf39e1d0f1
script: yarn run travis
cache: yarn
after_success:
  - cat coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - codeclimate-test-reporter < coverage/lcov.info
