init:
  - git config --global core.autocrlf true

environment:
  matrix:
  - nodejs_version: "0.12"
  - nodejs_version: 4
  - nodejs_version: 5
  - nodejs_version: 6

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: >-
      if ($env:nodejs_version -eq "0.12" -or $env:nodejs_version -eq "4") {
        npm -g install npm@3
        $env:PATH="$env:APPDATA\npm;$env:PATH"
      }
  - npm install

test_script:
  - node --version && npm --version
  - npm test

build: off

matrix:
  fast_finish: true
